# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d14017ce6007f2e621e95e1419e5fa8e5f09abd970303d4d2fd570bbdd90a34ba5187ee424f317ebc5853d9ae62f8ef7c85d8abfbf6f58fb04fd8a9ead471ff0

test:
  secret_key_base: 6c29db123581d123ca07a377a393cf84af8300d3941e94267428d49a5867988df302289a1f443a62d9bc74f9d14587195a841c57385e8261a4c790a3a0a45c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
